---
- name: install-bin | Update repositories cache on Ubuntu
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: install-bin | Install required packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  become: true
  with_items: '{{ rclone_packages }}'

- name: install-bin | Remove temporary working directory
  ansible.builtin.file:
    path: "{{ rclone_setup_tmp_dir }}"
    state: absent
  tags:
    - molecule-idempotence-notest

- name: install-bin | Create temporary working directory
  ansible.builtin.file:
    path: "{{ rclone_setup_tmp_dir }}"
    state: directory
    mode: '0775'

- name: install-bin | Do beta install
  include_tasks: beta.yml
  when: rclone_release == 'beta'

- name: install-bin | Do stable install
  include_tasks: stable.yml
  when: rclone_release == 'stable'

- name: install-bin | Get list of files extracted from the rclone archive
  ansible.builtin.find:
    path: "{{ rclone_setup_tmp_dir }}"
    depth: 2
    file_type: directory
  register: rclone_archive

- name: install-bin | Copy rclone binary
  ansible.builtin.copy:
    src: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}/rclone"
    dest: "/usr/local/bin/rclone"
    mode: '0755'
    owner: root
    group: root
    remote_src: true
  become: true

- name: install-bin | Make dir for local manpages
  ansible.builtin.file:
    path: '{{ rclone_man_pages.PATH }}'
    state: directory
    mode: '0775'
    owner: '{{ rclone_man_pages.OWNER }}'
    group: '{{ rclone_man_pages.GROUP }}'
  become: true
  when: install_manpages

- name: install-bin | Copy rclone manpage
  ansible.builtin.copy:
    src: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}/rclone.1"
    dest: "{{ rclone_man_pages.PATH }}/rclone.1"
    mode: '0644'
    owner: root
    group: root
    remote_src: true
  become: true
  when: install_manpages

- name: install-bin | Update mandb
  ansible.builtin.command: mandb
  become: true
  changed_when: false
  when: install_manpages
