---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts['os_family'] == 'Debian'
    - name: Wait for systemd to complete initialization.
      ansible.builtin.command:
        cmd: systemctl is-system-running
      changed_when: false
      delay: 5
      register: systemctl_status
      retries: 30
      until: "'running' in systemctl_status.stdout or 'degraded' in systemctl_status.stdout"
      when: ansible_facts['distribution'] == 'Fedora'
    - name: Show ansible version
      ansible.builtin.debug:
        msg: "Ansible Version: {{ ansible_version.full }}"

  roles:
    - role: buluma.rclone
