- become: true
  hosts: all
  name: Converge
  pre_tasks:
  - apt: update_cache=true cache_valid_time=600
    name: Update apt cache.
    when: ansible_os_family == 'Debian'
  - changed_when: false
    command: systemctl is-system-running
    delay: 5
    name: Wait for systemd to complete initialization.
    register: systemctl_status
    retries: 30
    until: '''running'' in systemctl_status.stdout or ''degraded'' in systemctl_status.stdout

      '
    when: ansible_distribution == 'Fedora'
  - ansible.builtin.debug:
      msg: 'Ansible Version: {{ ansible_version.full }}'
    name: Show ansible version
  roles:
  - role: buluma.rclone
