---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: rclone - retrieve information
      ansible.builtin.stat:
        path: /usr/local/bin/rclone
      register: remote_file
    - name: rclone - assert that file is created correctly
      ansible.builtin.assert:
        that:
          - remote_file.stat.exists
          - remote_file.stat.isreg
          - remote_file.stat.mode == '0755'
    - name: rclone - check version
      ansible.builtin.command:
        cmd: /usr/local/bin/rclone version
      changed_when: false
      register: shell_result
    - name: rclone - show version output
      ansible.builtin.debug:
        var: shell_result.stdout_lines
