- become: true
  gather_facts: true
  hosts: all
  name: Verify
  tasks:
  - ansible.builtin.stat:
      path: /usr/local/bin/rclone
    name: rclone - retrieve information
    register: remote_file
  - ansible.builtin.assert:
      that:
      - remote_file.stat.exists
      - remote_file.stat.isreg
      - remote_file.stat.mode == '0755'
    name: rclone - assert that file is created correctly
  - command: /usr/local/bin/rclone version
    name: rclone - check version
    register: shell_result
  - debug:
      var: shell_result.stdout_lines
